var model1 = {
  deg1:90,
  windowH:window.innerHeight,
  y1:0,
  y2:0,
  box1:function(boxSel,imgSel,pSel,arrow,personSel){
      setTimeout(function(){
          $(boxSel).css("visibility","visible");
          $(boxSel).addClass("transformLf");
      },500);
      setTimeout(function(){
          $(imgSel).show();
          $(imgSel).addClass("transformRt");
      },1000);
      setTimeout(function(){
          $(pSel).show();
          $(pSel).addClass("scale");
      },1500);
      setTimeout(function(){
          $(arrow).css("visibility","visible");
          $(arrow).addClass("translateTop");
      },2000)
      setTimeout(function(){
          $(personSel).css("visibility","visible");
          $(personSel).addClass("translateBottom");
      },2200)
  },
  box2:function(boxSel,p1Sel,p2Sel,p3Sel,zxcSel){
      setTimeout(function(){
          $(boxSel).css("visibility","visible");
          $(boxSel).addClass("scale");
      },500);
      setTimeout(function(){
          $(p1Sel).css("visibility","visible");
          $(p1Sel).addClass("scale");
      },1000)
      setTimeout(function(){
          $(p2Sel).css("visibility","visible");
          $(p2Sel).addClass("t2");
      },1500)
      setTimeout(function(){
          $(p3Sel).css("visibility","visible");
          $(p3Sel).addClass("translateBottom");
      },1500)
      setTimeout(function(){
          $(zxcSel).children("img").css("visibility","visible");
          $(zxcSel).css("visibility","visible");
          $(zxcSel).children("img").addClass("lfToRt");
      },2000)
  },
  box3:function(boxSel,sun,rainy,rainy1,h4Sel,txt_p,sound,zxc){
    setTimeout(function(){
      $(boxSel).css("visibility","visible");
      $(boxSel).addClass("opcScale");
      $(zxc).css("visibility","visible");
      $(zxc).addClass("lfToRt");
    },500)
    setTimeout(function(){
      $(sun).css("visibility","visible");
      $(sun).addClass("opcScale");
    },1000)
    setTimeout(function(){
      $(rainy).css("visibility","visible");
      $(rainy).addClass("lfToRt1");
      $(rainy1).css("visibility","visible");
      $(rainy1).addClass("RtTolf1");
      
    },1000)
    setTimeout(function(){
      $(h4Sel).css("visibility","visible");
      $(h4Sel).addClass("bounce");
    },2200)
    setTimeout(function(){
      $(txt_p).css("visibility","visible");
      $(txt_p).addClass("opc");
    },2500)
    setTimeout(function(){
      $(sound).css("visibility","visible");
      $(sound).addClass("scale_quick");
    },2900)
  },
  box4:function(boxSel,img1,box1,img2,box2,img3,shi,shiI,guang,guangI,tit,party,tree){
    setTimeout(function(){
        $(boxSel).css("visibility","visible");
        $(boxSel).addClass("transformLf");
    },500)
    setTimeout(function(){
        $(img1).css("visibility","visible");
        $(img1).addClass("transformRt");
        $(shi).css("visibility","visible");
        $(shi).addClass("lfToRt1");
    },1200)
    setTimeout(function(){
        $(box1).css("visibility","visible");
        $(box1).addClass("scale");
        $(guang).css("visibility","visible");
        $(guang).addClass("RtTolf1")
    },2500)
    setTimeout(function(){
        $(shiI).css("visibility","visible");
        $(shiI).addClass("bounce1");
    },2000)
    setTimeout(function(){
        $(img2).css("visibility","visible");
        $(img2).addClass("scaleBig");
    },3000)
    setTimeout(function(){
        $(guangI).css("visibility","visible");
        $(guangI).addClass("bounce1")
    },3500)
    setTimeout(function(){
        $(box2).css("visibility","visible");
        $(box2).addClass("bounce1");
        $(tit).css("visibility","visible");
        $(tit).addClass("scaleBig");
    },4000)
    setTimeout(function(){
        $(party).css("visibility","visible");
        $(party).addClass("opc");
        $(tree).css("visibility","visible");
        $(tree).addClass("btmToTop");
    },4500)
    setTimeout(function(){
        $(img3).css("visibility","visible");
        $(img3).addClass("bounce1");
    },4500)
  },
  box5:function(boxSel,yun,plane,gd){
    setTimeout(function(){
        $(boxSel).css("visibility","visible");
        $(boxSel).addClass("scaleBig2");
    },500)
    setTimeout(function(){
        $(yun).css("visibility","visible");
        $(yun).addClass("btmToTop");
    },1000)
    setTimeout(function(){
        $(plane).css("visibility","visible");
        $(plane).addClass("anim_plane");
        $(gd).css("visibility","visible");
        $(gd).addClass("anim_gd");
    },1500)
  },
  clk:function(){
    var _this = this;
      $("body")[0].addEventListener("touchstart",touch,false)
      $("body")[0].addEventListener("touchend",touch1,false)
      function touch(event){
          var e = event || window.event; 
          _this.y1 = e.touches[0].clientY
      }
      function touch1(event){
          var ind = $("body").attr("dataNum");
          var e = event || window.event; 
          _this.y2 = e.changedTouches[0].clientY;
          if(_this.y2<_this.y1){
            if(ind<5){
              ind++
              location.href="model"+ind+".html";
            }
          }else{
            if(ind>1){
              ind--
              location.href="model"+ind+".html";
            }
            
          }
      }
  },
  renderFn:function(){
    $("body").css("height",this.windowH);
      this.box1(".box1",".section1>img",".section1>p",".btm_arrow img",".person img");
      this.box2(".box2",".party",".text2",".text3",".zxc");
      this.box3(".box3",".sun",".rain2",".rain1",".text h4",".text p",".sound",".zxc");
      this.box4(".box4",".a4_1",".box_1",".a4_2",".box_2",".a4_3",".shi",".shi i",".guang",".guang i",".rt_txt h2",".rt_txt p",".tree");
      this.box5(".box5_img",".yun",".plane",".gd");
      this.clk();
  }
};
model1.renderFn();
